name: Maven Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload geoscript-js.zip
        uses: actions/upload-artifact@v2
        with:
          name: geoscript-js.zip
          path: target/geoscript-js-*.zip
      - name: Upload geoscript-js-app.jar
        uses: actions/upload-artifact@v2
        with:
          name: geoscript-js-app
          path: target/geoscript-js-*-app.jar